name: Unit tests
on: [push]
jobs:
  Run-backend-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      - name: npm install
        run: | 
          cd backend
          npm install
      - name: npm test
        run: | 
          cd backend
          npm test